// examples/vue-router/src/views/Orgs.vue
<script lang="ts">
import { routes } from '@/router';
import { parsePath } from 'typesafe-routes/vue-router';
import { useRoute,  } from 'vue-router'

const params = useRoute().params; // Record<string, RouteParamValue | RouteParamValue[]>
const parsedParams = parsePath(routes.orgs, params) // RouteParamValue[] array is the problem here
</script>

<template>
  <h2>Orgs</h2>
  <pre>params: {{JSON.stringify(parsedParams)}}</pre>
</template>

// examples/wouter/src/pages/Orgs.tsx
import { useParams } from "wouter";
import { routes } from "../routes";
import { parsePath } from "typesafe-routes";

export const Orgs = () => {
  const params = useParams();

  const parsedParams = parsePath(routes.orgs, params);

  return (
    <>
      <h2>Orgs</h2>
      <pre>params: {JSON.stringify(parsedParams)}</pre>
    </>
  );
}
