// examples/angular-router/src/app/app.component.ts
import { Component } from "@angular/core";
import { RouterOutlet, RouterLink } from "@angular/router";
import { render, renderPath } from "typesafe-routes/angular-router";
import { r } from "./app.routes";

@Component({
  selector: "app-root",
  imports: [RouterOutlet, RouterLink],
  template: `
    <h1>Absolute Links</h1>
    <ul>
      <li><a [routerLink]="dashboardLink">Dashboard</a></li>
      <li><a [routerLink]="orgsLink">Org</a></li>
      <li>
        <a [routerLink]="locationLink.path" [queryParams]="locationLink.query">
          Location
        </a>
      </li>
    </ul>
    <router-outlet></router-outlet>
  `,
})
export class AppComponent {
  dashboardLink = renderPath(r.dashboard, {});
  orgsLink = renderPath(r.orgs, { orgId: 123 });
  locationLink = render(r.orgs.locations, {
    path: { orgId: 321, locationId: 654 },
    query: { page: 42 },
  });
}

// examples/vue-router/src/App.vue
<script setup lang="ts">
import { render, renderPath } from 'typesafe-routes';
import { RouterLink, RouterView } from 'vue-router';
import { routes } from './router';
</script>

<template>
  <header>
    <nav>
      <RouterLink :to="renderPath(routes.dashboard, {})">Dashboard</RouterLink>
      <RouterLink :to="renderPath(routes.orgs, { orgId: 1 })">Orgs</RouterLink>
      <RouterLink
        :to="render(routes.orgs.locations, {
          path: { locationId: 42, orgId: 9 },
          query: { page: 5 }
        })"
      >
        Locations
      </RouterLink>
    </nav>
  </header>

  <RouterView />
</template>
