// examples/wouter/src/App.tsx
import { Link, Redirect, Route, Switch } from "wouter"
import { render, renderPath, template } from "typesafe-routes";
import { routes } from "./routes";
import { Dashboard } from "./pages/Dashboard";
import { Orgs } from "./pages/Orgs";
import { Locations } from "./pages/Locations";

export const App = () =>
  <>
    <ul>
      <li><Link to={renderPath(routes.dashboard, {})}>Dashboard</Link></li>
      <li><Link to={renderPath(routes.orgs, { orgId: 123 })}>Org</Link></li>
      <li>
        <Link
          to={render(routes.orgs.locations, {
            path: { orgId: 321, locationId: 12 },
            query: { page: 12 }
          })}
        >
          Location
        </Link>
      </li>
    </ul >
    <Switch>
      <Route path={template(routes.dashboard)}>
        <Dashboard />
      </Route>
      <Route path={template(routes.orgs)} nest>
        <Orgs />
        <Route path={template(routes.orgs._.locations)}>
          <Locations />
        </Route>
      </Route>
      <Route>
        <Redirect
          replace
          to={renderPath(routes.dashboard, {})}
        />
      </Route>
    </Switch>
  </>;

// examples/vue-router/src/App.vue
<script setup lang="ts">
import { render, renderPath } from 'typesafe-routes';
import { RouterLink, RouterView } from 'vue-router';
import { routes } from './router';
</script>

<template>
  <header>
    <nav>
      <RouterLink :to="renderPath(routes.dashboard, {})">Dashboard</RouterLink>
      <RouterLink :to="renderPath(routes.orgs, { orgId: 1 })">Orgs</RouterLink>
      <RouterLink
        :to="render(routes.orgs.locations, {
          path: { locationId: 42, orgId: 9 },
          query: { page: 5 }
        })"
      >
        Locations
      </RouterLink>
    </nav>
  </header>

  <RouterView />
</template>
